### ISSUE TITLE
Issue installing BOM Forecast Module 

### ISSUE THREAD

**Issue by craigmcewen** [DavidFW1960/bom_forecast#9]
Hi, 

Trying to setup the BOM Forecast module and I seem to be running into difficulty in getting it up and running :-( 

I have tried manual installation, installing through HACS and manually "helping" the installation by providing the template and sensors using the HACS install side by side, nothing I do seems to be working, I am running HA on Hyper V from the HA provided virtual disk, weather is setup and running as it should. 

The error that HA is throwing on each restart is:

``` 
2020-10-13 22:47:47 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up bom_forecast platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 193, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/bom_forecast/sensor.py", line 252, in setup_platform
    bom_forecast_data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/bom_forecast/sensor.py", line 489, in update
    ftp.retrbinary('RETR ' + self._product_id + '.xml', file_obj.write)
  File "/usr/local/lib/python3.8/ftplib.py", line 425, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.8/ftplib.py", line 382, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.8/ftplib.py", line 348, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "/usr/local/lib/python3.8/ftplib.py", line 275, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.8/ftplib.py", line 248, in getresp
    raise error_perm(resp)
ftplib.error_perm: 550 Failed to open file.
```

I am sure I am likely just doing something incorrect, any help you could provide would be much appreciated!

**Comment by craigmcewen** [comment]
Wouldn't you believe it, spent a few days trying to get it all going and minutes after I post for help I finally resolved the issue. 
For whatever reason the issue was with placing the station id inside the secrets file, once I entered the product ID and the name for the BOM_forecast module directly inside the sensor the setup was able to complete correctly.
